services:
  mysql:
    image: mysql:8.0
    container_name: weblinkshield-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: weblinkshield
      MYSQL_USER: ws
      MYSQL_PASSWORD: ws
    ports:
      - "3306:3306"
    command:
      - --default-authentication-plugin=mysql_native_password
      - --lower_case_table_names=1
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
